<?php
$state = $_POST['state'];

$districts = array();

if ($state == "UTTAR PRADESH") {
    $districts = array(
        array("value" => "AGRA", "text" => "AGRA आगरा"),
        array("value" => "ALIGARH", "text" => "ALIGARH अलीगढ़"),
        array("value" => "ALLAHABAD", "text" => "ALLAHABAD प्रयागराज"),
        array("value" => "AMBEDKAR NAGAR", "text" => "AMBEDKAR NAGAR अम्बेडकर नगर"),
        array("value" => "AMETHI", "text" => "AMETHI अमेठी"),
        array("value" => "AMROHA", "text" => "AMROHA अमरोहा"),
        array("value" => "AURAIYA", "text" => "AURAIYA औरैया"),
        array("value" => "AZAMGARH", "text" => "AZAMGARH आज़मगढ़"),
        array("value" => "BAGHPAT", "text" => "BAGHPAT बागपत"),
        array("value" => "BAHRAICH", "text" => "BAHRAICH बहराइच"),
        array("value" => "BALLIA", "text" => "BALLIA बलिया"),
        array("value" => "BALRAMPUR", "text" => "BALRAMPUR बलरामपुर"),
        array("value" => "BANDA", "text" => "BANDA बाँदा"),
        array("value" => "BARABANKI", "text" => "BARABANKI बाराबंकी"),
        array("value" => "BAREILLY", "text" => "BAREILLY बरेली"),
        array("value" => "BASTI", "text" => "BASTI बस्ती"),
        array("value" => "BIJNOR", "text" => "BIJNOR बिजनौर"),
        array("value" => "BUDAUN", "text" => "BUDAUN बदायूं"),
        array("value" => "BULANDSHAHR", "text" => "BULANDSHAHR बुलंदशहर"),
        array("value" => "CHANDAULI", "text" => "CHANDAULI चंदौली"),
        array("value" => "CHITRAKOOT", "text" => "CHITRAKOOT चित्रकूट"),
        array("value" => "DEORIA", "text" => "DEORIA देवरिया"),
        array("value" => "ETAH", "text" => "ETAH एटा"),
        array("value" => "ETAWAH", "text" => "ETAWAH इटावा"),
        array("value" => "FAIZABAD", "text" => "FAIZABAD अयोध्या"),
        array("value" => "FARRUKHABAD", "text" => "FARRUKHABAD फर्रुखाबाद"),
        array("value" => "FATEHPUR", "text" => "FATEHPUR फतेहपुर"),
        array("value" => "FIROZABAD", "text" => "FIROZABAD फिरोजाबाद"),
        array("value" => "GAUTAM BUDDHA NAGAR", "text" => "GAUTAM BUDDHA NAGAR गौतम बुद्ध नगर"),
        array("value" => "GHAZIABAD", "text" => "GHAZIABAD गाजियाबाद"),
        array("value" => "GHAZIPUR", "text" => "GHAZIPUR गाजीपुर"),
        array("value" => "GONDA", "text" => "GONDA गोंडा"),
        array("value" => "GORAKHPUR", "text" => "GORAKHPUR गोरखपुर"),
        array("value" => "HAMIRPUR", "text" => "HAMIRPUR हमीरपुर"),
        array("value" => "HAPUR", "text" => "HAPUR हापुड़"),
        array("value" => "HARDOI", "text" => "HARDOI हरदोई"),
        array("value" => "HATHRAS", "text" => "HATHRAS हाथरस"),
        array("value" => "JALAUN", "text" => "JALAUN जालौन"),
        array("value" => "JAUNPUR", "text" => "JAUNPUR जौनपुर"),
        array("value" => "JHANSI", "text" => "JHANSI झाँसी"),
        array("value" => "KANNAUJ", "text" => "KANNAUJ कन्नौज"),
        array("value" => "KANPUR DEHAT", "text" => "KANPUR DEHAT कानपुर देहात"),
        array("value" => "KANPUR NAGAR", "text" => "KANPUR NAGAR कानपुर नगर"),
        array("value" => "KASGANJ", "text" => "KASGANJ कासगंज"),
        array("value" => "KAUSHAMBI", "text" => "KAUSHAMBI कौशांबी"),
        array("value" => "KHERI", "text" => "KHERI खीरी"),
        array("value" => "KUSHINAGAR", "text" => "KUSHINAGAR कुशीनगर"),
        array("value" => "LALITPUR", "text" => "LALITPUR ललितपुर"),
        array("value" => "LUCKNOW", "text" => "LUCKNOW लखनऊ"),
        array("value" => "MAHARAJGANJ", "text" => "MAHARAJGANJ महाराजगंज"),
        array("value" => "MAHOBA", "text" => "MAHOBA महोबा"),
        array("value" => "MAINPURI", "text" => "MAINPURI मैनपुरी"),
        array("value" => "MATHURA", "text" => "MATHURA मथुरा"),
        array("value" => "MAU", "text" => "MAU मऊ"),
        array("value" => "MEERUT", "text" => "MEERUT मेरठ"),
        array("value" => "MIRZAPUR", "text" => "MIRZAPUR मिर्ज़ापुर"),
        array("value" => "MORADABAD", "text" => "MORADABAD मुरादाबाद"),
        array("value" => "MUZAFFARNAGAR", "text" => "MUZAFFARNAGAR मुज़फ्फरनगर"),
        array("value" => "PILIBHIT", "text" => "PILIBHIT पीलीभीत"),
        array("value" => "PRATAPGARH", "text" => "PRATAPGARH प्रतापगढ़"),
        array("value" => "RAE BARELI", "text" => "RAE BARELI रायबरेली"),
        array("value" => "RAMPUR", "text" => "RAMPUR रामपुर"),
        array("value" => "SAHARANPUR", "text" => "SAHARANPUR सहारनपुर"),
        array("value" => "SAMBHAL", "text" => "SAMBHAL सम्भल"),
        array("value" => "SANT KABEER NAGAR", "text" => "SANT KABEER NAGAR संत कबीर नगर"),
        array("value" => "SANT RAVIDAS NAGAR", "text" => "SANT RAVIDAS NAGAR संत रविदास नगर"),
        array("value" => "SHAHJAHANPUR", "text" => "SHAHJAHANPUR शाहजहाँपुर"),
        array("value" => "SHAMLI", "text" => "SHAMLI शामली"),
        array("value" => "SHRAVASTI", "text" => "SHRAVASTI श्रावस्ती"),
        array("value" => "SIDDHARTHNAGAR", "text" => "SIDDHARTHNAGAR सिद्धार्थनगर"),
        array("value" => "SITAPUR", "text" => "SITAPUR सीतापुर"),
        array("value" => "SONBHADRA", "text" => "SONBHADRA सोनभद्र"),
        array("value" => "SULTANPUR", "text" => "SULTANPUR सुल्तानपुर"),
        array("value" => "UNNAO", "text" => "UNNAO उन्नाव"),
        array("value" => "VARANASI", "text" => "VARANASI वाराणसी")
    );
} else if ($state === "BIHAR") {
    $districts = array(
        array("value" => "ARARIA", "text" => "Araria अररिया"),
        array("value" => "ARWAL", "text" => "Arwal अरवल"),
        array("value" => "AURANGABAD", "text" => "Aurangabad औरंगाबाद"),
        array("value" => "BANKA", "text" => "Banka बांका"),
        array("value" => "BEGUSARAI", "text" => "Begusarai बेगूसराय"),
        array("value" => "BHAGALPUR", "text" => "Bhagalpur भागलपुर"),
        array("value" => "BHOJPUR", "text" => "Bhojpur भोजपुर"),
        array("value" => "BUXAR", "text" => "Buxar बक्सर"),
        array("value" => "DARBHANGA", "text" => "Darbhanga दरभंगा"),
        array("value" => "EAST_CHAMPARAN", "text" => "East Champaran पूर्वी चंपारण"),
        array("value" => "GAYA", "text" => "Gaya गया"),
        array("value" => "GAZIPUR", "text" => "Gopalganj गोपालगंज"),
        array("value" => "JAMUI", "text" => "Jamui जमुई"),
        array("value" => "JEHANABAD", "text" => "Jehanabad जहानाबाद"),
        array("value" => "KAIMUR", "text" => "Kaimur कैमूर"),
        array("value" => "KATIHAR", "text" => "Katihar कटिहार"),
        array("value" => "KHAGARIA", "text" => "Khagaria खगड़िया"),
        array("value" => "KISHANGANJ", "text" => "Kishanganj किशनगंज"),
        array("value" => "LAKHISARAI", "text" => "Lakhisarai लखीसराय"),
        array("value" => "MADHEPURA", "text" => "Madhepura मधेपुरा"),
        array("value" => "MADHUBANI", "text" => "Madhubani मधुबनी"),
        array("value" => "MUNGER", "text" => "Munger मुंगेर"),
        array("value" => "MUZAFFARPUR", "text" => "Muzaffarpur मुज़फ्फरपुर"),
        array("value" => "NALANDA", "text" => "Nalanda नालंदा"),
        array("value" => "NAWADA", "text" => "Nawada नवादा"),
        array("value" => "PATNA", "text" => "Patna पटना"),
        array("value" => "PURNIA", "text" => "Purnia पूर्णिया"),
        array("value" => "ROHTAS", "text" => "Rohtas रोहतास"),
        array("value" => "SAHARSA", "text" => "Saharsa सहरसा"),
        array("value" => "SAMASTIPUR", "text" => "Samastipur समस्तीपुर"),
        array("value" => "SARAN", "text" => "Saran सारण"),
        array("value" => "SHEIKHPURA", "text" => "Sheikhpura शेखपुरा"),
        array("value" => "SHEOHAR", "text" => "Sheohar शिवहर"),
        array("value" => "SITAMARHI", "text" => "Sitamarhi सीतामढ़ी"),
        array("value" => "SIWAN", "text" => "Siwan सिवान"),
        array("value" => "SUPAUL", "text" => "Supaul सुपौल"),
        array("value" => "VAISHALI", "text" => "Vaishali वैशाली"),
        array("value" => "WEST_CHAMPARAN", "text" => "West Champaran पश्चिमी चंपारण")
    );
} else if ($state == "ANDHRA PRADESH") {
    $districts = array(
        array("value" => "ANANTHAPURAMU", "text" => "Ananthapuramu अनंतपुरम"),
        array("value" => "CHITTOOR", "text" => "Chittoor चित्तूर"),
        array("value" => "EAST_GODAVARI", "text" => "East Godavari पूर्व गोदावरी"),
        array("value" => "GUNTUR", "text" => "Guntur गुंटूर"),
        array("value" => "KRISHNA", "text" => "Krishna कृष्णा"),
        array("value" => "KURNOOL", "text" => "Kurnool कुरनूल"),
        array("value" => "NELLORE", "text" => "Nellore नेल्लोर"),
        array("value" => "PRAKASAM", "text" => "Prakasam प्रकाशम्"),
        array("value" => "SRIKAKULAM", "text" => "Srikakulam श्रीकाकुलम"),
        array("value" => "VISAKHAPATNAM", "text" => "Visakhapatnam विशाखापट्टनम"),
        array("value" => "VIZIANAGARAM", "text" => "Vizianagaram विजयनगरम"),
        array("value" => "WEST_GODAVARI", "text" => "West Godavari पश्चिम गोदावरी"),
        array("value" => "YSR_KADAPA", "text" => "YSR Kadapa वाय.एस.आर. कडप्पा"),
        array("value" => "ANNAMAYYA", "text" => "Annamayya अन्नमय्या"),
        array("value" => "ANAKAPALLE", "text" => "Anakapalle अनकापल्ली"),
        array("value" => "BAPATLA", "text" => "Bapatla बापटला"),
        array("value" => "ELURU", "text" => "Eluru एलुरु"),
        array("value" => "KAKINADA", "text" => "Kakinada काकीनाडा"),
        array("value" => "KONA_SEEMA", "text" => "Konaseema कोनसीमा"),
        array("value" => "NALGONDA", "text" => "Nandyal नंद्याल"),  // Typo corrected below
        array("value" => "NTR", "text" => "NTR एनटीआर"),
        array("value" => "PALNADU", "text" => "Palnadu पलनाडु"),
        array("value" => "PARVATHIPURAM_MANYAM", "text" => "Parvathipuram Manyam पर्वतीपुरम मन्यम"),
        array("value" => "SRI_SATHYA_SAI", "text" => "Sri Sathya Sai श्री सत्य साई"),
        array("value" => "TIRUPATI", "text" => "Tirupati तिरुपति"),
        array("value" => "VIZIANAGARAM", "text" => "Vizianagaram विजयनगरम")
    );
} else if ($state == "ARUNACHAL PRADESH") {
    $districts = array(
        array("value" => "TAWANG", "text" => "Tawang तवांग"),
        array("value" => "WEST_KAMENG", "text" => "West Kameng पश्चिम कामेंग"),
        array("value" => "EAST_KAMENG", "text" => "East Kameng पूर्वी कामेंग"),
        array("value" => "PAPUM_PARE", "text" => "Papum Pare पापुम पारे"),
        array("value" => "KURUNG_KUMEY", "text" => "Kurung Kumey कुरुंग कुमे"),
        array("value" => "KRA_DAADI", "text" => "Kra Daadi क्रा दादी"),
        array("value" => "LOWER_SUBANSIRI", "text" => "Lower Subansiri निचला सुबनसिरी"),
        array("value" => "UPPER_SUBANSIRI", "text" => "Upper Subansiri ऊपरी सुबनसिरी"),
        array("value" => "WEST_SIANG", "text" => "West Siang पश्चिम सियांग"),
        array("value" => "EAST_SIANG", "text" => "East Siang पूर्वी सियांग"),
        array("value" => "UPPER_SIANG", "text" => "Upper Siang ऊपरी सियांग"),
        array("value" => "SIANG", "text" => "Siang सियांग"),
        array("value" => "LOWER_SIANG", "text" => "Lower Siang निचला सियांग"),
        array("value" => "LOWER_DIBANG_VALLEY", "text" => "Lower Dibang Valley निचली दिबांग घाटी"),
        array("value" => "DIBANG_VALLEY", "text" => "Dibang Valley दिबांग घाटी"),
        array("value" => "LOHIT", "text" => "Lohit लोहित"),
        array("value" => "ANJAW", "text" => "Anjaw अंजॉ"),
        array("value" => "CHANGELANG", "text" => "Changlang चांगलांग"),
        array("value" => "TIRAP", "text" => "Tirap तिराप"),
        array("value" => "NAMSAI", "text" => "Namsai नामसाई"),
        array("value" => "KAMLE", "text" => "Kamle कामले"),
        array("value" => "LEPARADA", "text" => "Lepa Rada लेपा राडा"),
        array("value" => "PAKKE_KESSANG", "text" => "Pakke Kessang पक्के केसांग"),
        array("value" => "SHI_YOMI", "text" => "Shi Yomi शी योमी"),
        array("value" => "KURUNG_KUMEY", "text" => "Kurung Kumey कुरुंग कुमे"),
        array("value" => "ITANAGAR_CAPITAL", "text" => "Itanagar Capital ईटानगर राजधानी")
    );
} else if ($state == "ASSAM") {

    $districts = array(
        array("value" => "BAKSA", "text" => "Baksa बकसा"),
        array("value" => "BARPETA", "text" => "Barpeta बारपेटा"),
        array("value" => "BISWANATH", "text" => "Biswanath बिस्वनाथ"),
        array("value" => "BONGAIGAON", "text" => "Bongaigaon बोंगाईगांव"),
        array("value" => "CACHAR", "text" => "Cachar काछार"),
        array("value" => "CHARAIDEO", "text" => "Charaideo चराइदेओ"),
        array("value" => "CHIRANG", "text" => "Chirang चिरांग"),
        array("value" => "DARRANG", "text" => "Darrang डाररंग"),
        array("value" => "DHEMAJI", "text" => "Dhemaji धेमाजी"),
        array("value" => "DHUBRI", "text" => "Dhubri धुबरी"),
        array("value" => "DIBRUGARH", "text" => "Dibrugarh डिब्रूगढ़"),
        array("value" => "GOALPARA", "text" => "Goalpara गोलपारा"),
        array("value" => "GOLAGHAT", "text" => "Golaghat गोलाघाट"),
        array("value" => "HAILAKANDI", "text" => "Hailakandi हाइलाकांडी"),
        array("value" => "HOJAI", "text" => "Hojai होजाई"),
        array("value" => "JORHAT", "text" => "Jorhat जोरहाट"),
        array("value" => "KAMLE", "text" => "Kamle कामले"), // As requested
        array("value" => "KAMRUP", "text" => "Kamrup कामरूप"),
        array("value" => "KAMRUP METRO", "text" => "Kamrup Metro कामरूप मेट्रो"),
        array("value" => "KARBI ANGLONG", "text" => "Karbi Anglong कारबी आंगलोंग"),
        array("value" => "KARIMGANJ", "text" => "Karimganj करीमगंज"),
        array("value" => "KOKRAJHAR", "text" => "Kokrajhar कोकराझार"),
        array("value" => "LAKHIMPUR", "text" => "Lakhimpur लखीमपुर"),
        array("value" => "MAJULI", "text" => "Majuli माजुली"),
        array("value" => "MORIGAON", "text" => "Morigaon मोरीगांव"),
        array("value" => "NAGAON", "text" => "Nagaon नागांव"),
        array("value" => "NALBARI", "text" => "Nalbari नलबाड़ी"),
        array("value" => "SIVASAGAR", "text" => "Sivasagar शिवसागर"),
        array("value" => "SONITPUR", "text" => "Sonitpur सोनितपुर"),
        array("value" => "SOUTH SALMARA", "text" => "South Salmara दक्षिण सलमारा"),
        array("value" => "TINSUKIA", "text" => "Tinsukia तिनसुकिया"),
        array("value" => "UDALGURI", "text" => "Udalguri उदालगुड़ी"),
        array("value" => "WEST KARBI ANGLONG", "text" => "West Karbi Anglong पश्चिम कारबी आंगलोंग")
    );
} else if ($state == "CHHATTISGARH") {
    $districts = array(
        array("value" => "RAIPUR", "text" => "Raipur रायपुर"),
        array("value" => "BALOD", "text" => "Balod बालोद"),
        array("value" => "BALODA_BAZAR", "text" => "Baloda Bazar बलौदा बाजार"),
        array("value" => "BALRAMPUR", "text" => "Balrampur बलरामपुर"),
        array("value" => "BASTAR", "text" => "Bastar बस्तर"),
        array("value" => "BEMETARA", "text" => "Bemetara बेमेतरा"),
        array("value" => "BIJAPUR", "text" => "Bijapur बीजापुर"),
        array("value" => "BILASPUR", "text" => "Bilaspur बिलासपुर"),
        array("value" => "DANTEWADA", "text" => "Dantewada दंतेवाड़ा"),
        array("value" => "DHAMTARI", "text" => "Dhamtari धमतरी"),
        array("value" => "DURG", "text" => "Durg दुर्ग"),
        array("value" => "GARIABAND", "text" => "Gariaband गरियाबंद"),
        array("value" => "GAURELA_PENDRA_MARWAHI", "text" => "Gaurela-Pendra-Marwahi गौरेला-पेंड्रा-मरवाही"),
        array("value" => "JANJGIR_CHAMPA", "text" => "Janjgir-Champa जांजगीर-चांपा"),
        array("value" => "JASHPUR", "text" => "Jashpur जशपुर"),
        array("value" => "KABIRDHAM", "text" => "Kabirdham कबीरधाम"),
        array("value" => "KANKER", "text" => "Kanker कांकेर"),
        array("value" => "KONDAGAON", "text" => "Kondagaon कोंडागांव"),
        array("value" => "KORBA", "text" => "Korba कोरबा"),
        array("value" => "KOREA", "text" => "Korea कोरिया"),
        array("value" => "MAHASAMUND", "text" => "Mahasamund महासमुंद"),
        array("value" => "MUNGELI", "text" => "Mungeli मुंगेली"),
        array("value" => "NARAYANPUR", "text" => "Narayanpur नारायणपुर"),
        array("value" => "RAIGARH", "text" => "Raigarh रायगढ़"),
        array("value" => "RAJNANDGAON", "text" => "Rajnandgaon राजनांदगांव"),
        array("value" => "SUKMA", "text" => "Sukma सुकमा"),
        array("value" => "SURAJPUR", "text" => "Surajpur सूरजपुर"),
        array("value" => "SURENDRANAGAR", "text" => "Surajpur सूरजपुर"), // (Duplicate correction needed)
        array("value" => "SURGUJA", "text" => "Surguja सरगुजा"),
        array("value" => "MANENDRAGARH_CHIRIMIRI_BHARATPUR", "text" => "Manendragarh-Chirimiri-Bharatpur मनेंद्रगढ़-चिरमिरी-भरतपुर"),
        array("value" => "MOHALA_MANPUR", "text" => "Mohala-Manpur मोहला-मानपुर"),
        array("value" => "SAJA", "text" => "Saja साजा"),
        array("value" => "KHAIRAGARH", "text" => "Khairagarh खैरागढ़"),
        array("value" => "SARAI_PALI", "text" => "Sarai Pali सारायपाली")
    );
} else if ($state == 'GOA') {

    $districts = array(
        array("value" => "NORTH GOA", "text" => "North Goa उत्तर गोवा"),
        array("value" => "SOUTH GOA", "text" => "South Goa दक्षिण गोवा")
    );
} else if ($state == 'GUJARAT') {

    $districts = array(
        array("value" => "AHMEDABAD", "text" => "Ahmedabad अहमदाबाद"),
        array("value" => "AMRELI", "text" => "Amreli अमरेली"),
        array("value" => "ANAND", "text" => "Anand आणंद"),
        array("value" => "ARAVALLI", "text" => "Aravalli अरावली"),
        array("value" => "BANASKANTHA", "text" => "Banaskantha बनासकांठा"),
        array("value" => "BHARUCH", "text" => "Bharuch भरूच"),
        array("value" => "BHAVNAGAR", "text" => "Bhavnagar भावनगर"),
        array("value" => "BOTAD", "text" => "Botad बोटाद"),
        array("value" => "CHHOTA_UDAIPUR", "text" => "Chhota Udaipur छोटा उदेपुर"),
        array("value" => "DAHOD", "text" => "Dahod दाहोद"),
        array("value" => "DANG", "text" => "Dang डांग"),
        array("value" => "DEVBHOOMI_DWARKA", "text" => "Devbhoomi Dwarka देवभूमि द्वारका"),
        array("value" => "GANDHINAGAR", "text" => "Gandhinagar गांधीनगर"),
        array("value" => "GIR_SOMNATH", "text" => "Gir Somnath गिर सोमनाथ"),
        array("value" => "JAMNAGAR", "text" => "Jamnagar जामनगर"),
        array("value" => "JUNAGADH", "text" => "Junagadh जूनागढ़"),
        array("value" => "KACHCHH", "text" => "Kachchh कच्छ"),
        array("value" => "KHEDA", "text" => "Kheda खेड़ा"),
        array("value" => "MAHISAGAR", "text" => "Mahisagar महिसागर"),
        array("value" => "MEHSANA", "text" => "Mehsana मेहसाणा"),
        array("value" => "MORBI", "text" => "Morbi मोरबी"),
        array("value" => "NARMADA", "text" => "Narmada नर्मदा"),
        array("value" => "NAVSARI", "text" => "Navsari नवसारी"),
        array("value" => "PANCHMAHAL", "text" => "Panchmahal पंचमहल"),
        array("value" => "PATAN", "text" => "Patan पाटण"),
        array("value" => "PORBANDAR", "text" => "Porbandar पोरबंदर"),
        array("value" => "RAJKOT", "text" => "Rajkot राजकोट"),
        array("value" => "SABARKANTHA", "text" => "Sabarkantha साबरकांठा"),
        array("value" => "SURAT", "text" => "Surat सूरत"),
        array("value" => "SURENDRANAGAR", "text" => "Surendranagar सुरेन्द्रनगर"),
        array("value" => "TAPI", "text" => "Tapi तापी"),
        array("value" => "VADODARA", "text" => "Vadodara वडोदरा"),
        array("value" => "VALSAD", "text" => "Valsad वलसाड")
    );
} else if ($state == "HARYANA ") {
    $districts = array(
        array("value" => "AMBALA", "text" => "Ambala अंबाला"),
        array("value" => "BHIWANI", "text" => "Bhiwani भिवानी"),
        array("value" => "CHARKHI DADRI", "text" => "Charkhi Dadri चरखी दादरी"),
        array("value" => "FARIDABAD", "text" => "Faridabad फरीदाबाद"),
        array("value" => "FATEHABAD", "text" => "Fatehabad फतेहाबाद"),
        array("value" => "GURUGRAM", "text" => "Gurugram गुरुग्राम"),
        array("value" => "HISAR", "text" => "Hisar हिसार"),
        array("value" => "JHAJJAR", "text" => "Jhajjar झज्जर"),
        array("value" => "JIND", "text" => "Jind जींद"),
        array("value" => "KAITHAL", "text" => "Kaithal कैथल"),
        array("value" => "KARNAL", "text" => "Karnal करनाल"),
        array("value" => "KURUKSHETRA", "text" => "Kurukshetra कुरुक्षेत्र"),
        array("value" => "MAHENDRAGARH", "text" => "Mahendragarh महेंद्रगढ़"),
        array("value" => "NUH", "text" => "Nuh नूंह"),
        array("value" => "PALWAL", "text" => "Palwal पलवल"),
        array("value" => "PANCHKULA", "text" => "Panchkula पंचकूला"),
        array("value" => "PANIPAT", "text" => "Panipat पानीपत"),
        array("value" => "REWARI", "text" => "Rewari रेवाड़ी"),
        array("value" => "ROHTAK", "text" => "Rohtak रोहतक"),
        array("value" => "SIRSA", "text" => "Sirsa सिरसा"),
        array("value" => "SONIPAT", "text" => "Sonipat सोनीपत"),
        array("value" => "YAMUNANAGAR", "text" => "Yamunanagar यमुनानगर")
    );
} else if ($state == "HIMACHAL") {
    $districts = array(
        array("value" => "BILASPUR", "text" => "Bilaspur बिलासपुर"),
        array("value" => "CHAMBA", "text" => "Chamba चंबा"),
        array("value" => "HAMIRPUR", "text" => "Hamirpur हमीरपुर"),
        array("value" => "KANGRA", "text" => "Kangra कांगड़ा"),
        array("value" => "KINNAUR", "text" => "Kinnaur किन्नौर"),
        array("value" => "KULLU", "text" => "Kullu कुल्लू"),
        array("value" => "LAHAUL_AND_SPITI", "text" => "Lahaul and Spiti लाहौल और स्पीति"),
        array("value" => "MANDI", "text" => "Mandi मंडी"),
        array("value" => "SHIMLA", "text" => "Shimla शिमला"),
        array("value" => "SIRMAUR", "text" => "Sirmaur सिरमौर"),
        array("value" => "SOLAN", "text" => "Solan सोलन"),
        array("value" => "UNA", "text" => "Una ऊना")
    );
} else if ($state == "JHARKHAND") {
    $districts = array(
        array("value" => "BOKARO", "text" => "Bokaro बोकारो"),
        array("value" => "CHATRA", "text" => "Chatra चतरा"),
        array("value" => "DEOGHAR", "text" => "Deoghar देवघर"),
        array("value" => "DHANBAD", "text" => "Dhanbad धनबाद"),
        array("value" => "DUMKA", "text" => "Dumka दुमका"),
        array("value" => "EAST SINGHBUM", "text" => "East Singhbhum पूर्वी सिंहभूम"),
        array("value" => "GARHWA", "text" => "Garhwa गढ़वा"),
        array("value" => "GIRIDIH", "text" => "Giridih गिरिडीह"),
        array("value" => "GODDA", "text" => "Godda गोड्डा"),
        array("value" => "GUMLA", "text" => "Gumla गुमला"),
        array("value" => "HAZARIBAGH", "text" => "Hazaribagh हजारीबाग"),
        array("value" => "JAMTARA", "text" => "Jamtara जामताड़ा"),
        array("value" => "KHUNTI", "text" => "Khunti खूंटी"),
        array("value" => "KODERMA", "text" => "Koderma कोडरमा"),
        array("value" => "LATEHAR", "text" => "Latehar लातेहार"),
        array("value" => "LOHARDAGA", "text" => "Lohardaga लोहरदगा"),
        array("value" => "PAKUR", "text" => "Pakur पाकुड़"),
        array("value" => "PALAMU", "text" => "Palamu पलामू"),
        array("value" => "RAMGARH", "text" => "Ramgarh रामगढ़"),
        array("value" => "RANCHI", "text" => "Ranchi रांची"),
        array("value" => "SAHEBGANJ", "text" => "Sahebganj साहिबगंज"),
        array("value" => "SARAIKELA KHARSAWAN", "text" => "Saraikela Kharsawan सरायकेला खरसावां"),
        array("value" => "SIMDEGA", "text" => "Simdega सिमडेगा"),
        array("value" => "WEST SINGHBUM", "text" => "West Singhbhum पश्चिमी सिंहभूम")
    );
} else if ($state == "KARNATAKA") {
    $districts = array(
        array("value" => "BAGALKOT", "text" => "Bagalkot बागलकोट"),
        array("value" => "BALLARI", "text" => "Ballari बल्लारी"),
        array("value" => "BELAGAVI", "text" => "Belagavi बेलगावी"),
        array("value" => "BENGALURU_RURAL", "text" => "Bengaluru Rural बेंगलुरु ग्रामीण"),
        array("value" => "BENGALURU_URBAN", "text" => "Bengaluru Urban बेंगलुरु शहरी"),
        array("value" => "BIDAR", "text" => "Bidar बीदर"),
        array("value" => "CHAMARAJANAGAR", "text" => "Chamarajanagar चामराजनगर"),
        array("value" => "CHIKKABALLAPUR", "text" => "Chikkaballapur चिक्कबल्लापुर"),
        array("value" => "CHIKKAMAGALURU", "text" => "Chikkamagaluru चिक्कमंगलूर"),
        array("value" => "CHITRADURGA", "text" => "Chitradurga चित्रदुर्ग"),
        array("value" => "DAKSHINA_KANNADA", "text" => "Dakshina Kannada दक्षिण कन्नड़"),
        array("value" => "DAVANAGERE", "text" => "Davanagere दावणगेरे"),
        array("value" => "DHARWAD", "text" => "Dharwad धारवाड़"),
        array("value" => "GADAG", "text" => "Gadag गदग"),
        array("value" => "HASSAN", "text" => "Hassan हासन"),
        array("value" => "HAVERI", "text" => "Haveri हावेरी"),
        array("value" => "KALABURAGI", "text" => "Kalaburagi कलबुर्गी"),
        array("value" => "KODAGU", "text" => "Kodagu कोडागु"),
        array("value" => "KOLAR", "text" => "Kolar कोलार"),
        array("value" => "KOPPAL", "text" => "Koppal कोप्पल"),
        array("value" => "MANDYA", "text" => "Mandya मांड्या"),
        array("value" => "MYSURU", "text" => "Mysuru मैसूरु"),
        array("value" => "RAICHUR", "text" => "Raichur रायचूर"),
        array("value" => "RAMANAGARA", "text" => "Ramanagara रामनगर"),
        array("value" => "SHIVAMOGGA", "text" => "Shivamogga शिवमोग्गा"),
        array("value" => "TUMAKURU", "text" => "Tumakuru तुमकुरु"),
        array("value" => "UDUPI", "text" => "Udupi उडुपी"),
        array("value" => "UTTARA_KANNADA", "text" => "Uttara Kannada उत्तर कन्नड़"),
        array("value" => "VIJAYAPURA", "text" => "Vijayapura विजयपुर"),
        array("value" => "YADGIR", "text" => "Yadgir यादगीर"),
        array("value" => "VIJAYANAGARA", "text" => "Vijayanagara विजयनगर")
    );
} else if ($state == "KERALA") {
    $districts = array(
        array("value" => "ALAPPUZHA", "text" => "Alappuzha आलाप्पुझा"),
        array("value" => "ERNAKULAM", "text" => "Ernakulam एर्नाकुलम"),
        array("value" => "IDUKKI", "text" => "Idukki इडुक्की"),
        array("value" => "KANNUR", "text" => "Kannur कन्नूर"),
        array("value" => "KASARAGOD", "text" => "Kasaragod कासरगोड"),
        array("value" => "KOLLAM", "text" => "Kollam कोल्लम"),
        array("value" => "KOTTAYAM", "text" => "Kottayam कोट्टायम"),
        array("value" => "KOZHIKODE", "text" => "Kozhikode कोझिकोड"),
        array("value" => "MALAPPURAM", "text" => "Malappuram मलप्पुरम"),
        array("value" => "PALAKKAD", "text" => "Palakkad पलक्कड़"),
        array("value" => "PATHANAMTHITTA", "text" => "Pathanamthitta पथनमथिट्टा"),
        array("value" => "THIRUVANANTHAPURAM", "text" => "Thiruvananthapuram तिरुवनंतपुरम"),
        array("value" => "THRISSUR", "text" => "Thrissur त्रिशूर"),
        array("value" => "WAYANAD", "text" => "Wayanad वयनाड")
    );
} else if ($state == "MADHYA PRADESH") {
    $districts = array(
        array("value" => "AGAR_MALWA", "text" => "Agar Malwa आगर मालवा"),
        array("value" => "ALIRAJPUR", "text" => "Alirajpur अलीराजपुर"),
        array("value" => "ANUPPUR", "text" => "Anuppur अनूपपुर"),
        array("value" => "ASHOKNAGAR", "text" => "Ashoknagar अशोकनगर"),
        array("value" => "BALAGHAT", "text" => "Balaghat बालाघाट"),
        array("value" => "BARWANI", "text" => "Barwani बड़वानी"),
        array("value" => "BETUL", "text" => "Betul बैतूल"),
        array("value" => "BHIND", "text" => "Bhind भिंड"),
        array("value" => "BHOPAL", "text" => "Bhopal भोपाल"),
        array("value" => "BURHANPUR", "text" => "Burhanpur बुरहानपुर"),
        array("value" => "CHHATARPUR", "text" => "Chhatarpur छतरपुर"),
        array("value" => "CHHINDWARA", "text" => "Chhindwara छिंदवाड़ा"),
        array("value" => "DAMOH", "text" => "Damoh दमोह"),
        array("value" => "DATIA", "text" => "Datia दतिया"),
        array("value" => "DEWAS", "text" => "Dewas देवास"),
        array("value" => "DHAR", "text" => "Dhar धार"),
        array("value" => "DINDORI", "text" => "Dindori डिंडोरी"),
        array("value" => "GUNA", "text" => "Guna गुना"),
        array("value" => "GWALIOR", "text" => "Gwalior ग्वालियर"),
        array("value" => "HARDA", "text" => "Harda हरदा"),
        array("value" => "HOSHANGABAD", "text" => "Hoshangabad होशंगाबाद"),
        array("value" => "INDORE", "text" => "Indore इंदौर"),
        array("value" => "JABALPUR", "text" => "Jabalpur जबलपुर"),
        array("value" => "JHABUA", "text" => "Jhabua झाबुआ"),
        array("value" => "KATNI", "text" => "Katni कटनी"),
        array("value" => "KHANDWA", "text" => "Khandwa खंडवा"),
        array("value" => "KHARGONE", "text" => "Khargone खरगोन"),
        array("value" => "MANDLA", "text" => "Mandla मंडला"),
        array("value" => "MANDSAUR", "text" => "Mandsaur मंदसौर"),
        array("value" => "MORENA", "text" => "Morena मुरैना"),
        array("value" => "NARSINGHPUR", "text" => "Narsinghpur नरसिंहपुर"),
        array("value" => "NEEMUCH", "text" => "Neemuch नीमच"),
        array("value" => "NIWARI", "text" => "Niwari निवाड़ी"),
        array("value" => "PANNA", "text" => "Panna पन्ना"),
        array("value" => "RAISEN", "text" => "Raisen रायसेन"),
        array("value" => "RAJGARH", "text" => "Rajgarh राजगढ़"),
        array("value" => "RATLAM", "text" => "Ratlam रतलाम"),
        array("value" => "REWA", "text" => "Rewa रीवा"),
        array("value" => "RAJGARH", "text" => "Rajgarh राजगढ़"),
        array("value" => "SAGAR", "text" => "Sagar सागर"),
        array("value" => "SATNA", "text" => "Satna सतना"),
        array("value" => "SEHORE", "text" => "Sehore सीहोर"),
        array("value" => "SEONI", "text" => "Seoni सिवनी"),
        array("value" => "SHAHDOL", "text" => "Shahdol शहडोल"),
        array("value" => "SHAJAPUR", "text" => "Shajapur शाजापुर"),
        array("value" => "SHEOPUR", "text" => "Sheopur श्योपुर"),
        array("value" => "SHIVPURI", "text" => "Shivpuri शिवपुरी"),
        array("value" => "SIDHI", "text" => "Sidhi सीधी"),
        array("value" => "SINGRAULI", "text" => "Singrauli सिंगरौली"),
        array("value" => "TIKAMGARH", "text" => "Tikamgarh टीकमगढ़"),
        array("value" => "UJJAIN", "text" => "Ujjain उज्जैन"),
        array("value" => "UMARIA", "text" => "Umaria उमरिया"),
        array("value" => "VIDISHA", "text" => "Vidisha विदिशा")
    );
} else if ($state == "MAHARASHTRA") {
    $districts = array(
        array("value" => "ALAPPUZHA", "text" => "Alappuzha आलाप्पुझा"),
        array("value" => "ERNAKULAM", "text" => "Ernakulam एर्नाकुलम"),
        array("value" => "IDUKKI", "text" => "Idukki इडुक्की"),
        array("value" => "KANNUR", "text" => "Kannur कन्नूर"),
        array("value" => "KASARAGOD", "text" => "Kasaragod कासरगोड"),
        array("value" => "KOLLAM", "text" => "Kollam कोल्लम"),
        array("value" => "KOTTAYAM", "text" => "Kottayam कोट्टायम"),
        array("value" => "KOZHIKODE", "text" => "Kozhikode कोझिकोड"),
        array("value" => "MALAPPURAM", "text" => "Malappuram मलप्पुरम"),
        array("value" => "PALAKKAD", "text" => "Palakkad पलक्कड़"),
        array("value" => "PATHANAMTHITTA", "text" => "Pathanamthitta पथनमथिट्टा"),
        array("value" => "THIRUVANANTHAPURAM", "text" => "Thiruvananthapuram तिरुवनंतपुरम"),
        array("value" => "THRISSUR", "text" => "Thrissur त्रिशूर"),
        array("value" => "WAYANAD", "text" => "Wayanad वयनाड")
    );
} else if ($state == "MANIPUR") {
    $districts = array(
        array("value" => "BISHNUPUR", "text" => "Bishnupur बिष्णुपुर"),
        array("value" => "CHANDEL", "text" => "Chandel चandel"),
        array("value" => "CHURACHANDPUR", "text" => "Churachandpur चुराचांदपुर"),
        array("value" => "IMPHAL_EAST", "text" => "Imphal East इम्फाल ईस्ट"),
        array("value" => "IMPHAL_WEST", "text" => "Imphal West इम्फाल वेस्ट"),
        array("value" => "JIRIBAM", "text" => "Jiribam जिरीबाम"),
        array("value" => "KAKCHING", "text" => "Kakching ककचिंग"),
        array("value" => "KAMJONG", "text" => "Kamjong कमजोंग"),
        array("value" => "KANGPOKPI", "text" => "Kangpokpi कांगपोकपी"),
        array("value" => "NONEY", "text" => "Noney नोनी"),
        array("value" => "PHERZAWL", "text" => "Pherzawl फेर्ज़ावल"),
        array("value" => "SENAPATI", "text" => "Senapati सेनापति"),
        array("value" => "TAMENGLONG", "text" => "Tamenglong तमेंगलोंग"),
        array("value" => "TENGNOUPAL", "text" => "Tengnoupal तेंगनौपाल"),
        array("value" => "THOUBAL", "text" => "Thoubal थौबल"),
        array("value" => "UKHRUL", "text" => "Ukhrul उखरूल")
    );
} else if ($state == "MEGHALAYA") {
    $districts = array(
        array("value" => "EAST_KHASI_HILLS", "text" => "East Khasi Hills पूर्व खासी हिल्स"),
        array("value" => "SOUTH_KHASI_HILLS", "text" => "South Khasi Hills दक्षिण खासी हिल्स"),
        array("value" => "WEST_KHASI_HILLS", "text" => "West Khasi Hills पश्चिम खासी हिल्स"),
        array("value" => "EAST_JAINTIA_HILLS", "text" => "East Jaintia Hills पूर्व जयंतिया हिल्स"),
        array("value" => "WEST_JAINTIA_HILLS", "text" => "West Jaintia Hills पश्चिम जयंतिया हिल्स"),
        array("value" => "RIBHOI", "text" => "Ribhoi रिबोई"),
        array("value" => "SOUTH_WEST_KHASI_HILLS", "text" => "South West Khasi Hills दक्षिण पश्चिम खासी हिल्स"),
        array("value" => "SOUTH_WEST_GARO_HILLS", "text" => "South West Garo Hills दक्षिण पश्चिम गारो हिल्स"),
        array("value" => "WEST_GARO_HILLS", "text" => "West Garo Hills पश्चिम गारो हिल्स"),
        array("value" => "EAST_GARO_HILLS", "text" => "East Garo Hills पूर्व गारो हिल्स"),
        array("value" => "NORTH_GARO_HILLS", "text" => "North Garo Hills उत्तर गारो हिल्स")
    );
} else if ($state == "MIZORAM") {
    $districts = array(
        array("value" => "AIZAWL", "text" => "Aizawl आिज़ावल"),
        array("value" => "CHAMPHAI", "text" => "Champhai चम्फाई"),
        array("value" => "HAUHLU", "text" => "Hnahthial हनथियल"),
        array("value" => "KOLASIB", "text" => "Kolasib कोलासिब"),
        array("value" => "LAWNGTLAI", "text" => "Lawngtlai लॉन्गतलाई"),
        array("value" => "LUNGLEI", "text" => "Lunglei लुंगलेई"),
        array("value" => "MAMIT", "text" => "Mamit ममित"),
        array("value" => "SAIHA", "text" => "Saiha साईहा"),
        array("value" => "SERCHHIP", "text" => "Serchhip सर्चिप"),
        array("value" => "SIAHA", "text" => "Siaha सिआहा"),
        array("value" => "WEST_KHAWI", "text" => "West Khawi पश्चिम खावि")
    );
} else if ($state == "NAGALAND") {

    $districts = array(
        array("value" => "DIMAPUR", "text" => "Dimapur डिमापुर"),
        array("value" => "KOHIMA", "text" => "Kohima कोहिमा"),
        array("value" => "MOKOKCHUNG", "text" => "Mokokchung मोकोकचुंग"),
        array("value" => "MON", "text" => "Mon मोन"),
        array("value" => "NOKLAK", "text" => "Noklak नोक्तलाक"),
        array("value" => "PHEK", "text" => "Phek फेक"),
        array("value" => "TUENSANG", "text" => "Tuensang तुएन्सांग"),
        array("value" => "ZUNHEBOTO", "text" => "Zunheboto जुन्हेबोटो")
    );
} else if ($state == "ODISHA") {
    $districts = array(
        array("value" => "ANGUL", "text" => "Angul अंगुल"),
        array("value" => "BALANGIR", "text" => "Balangir बलांगीर"),
        array("value" => "BALASORE", "text" => "Balasore बालासोर"),
        array("value" => "BARGARH", "text" => "Bargarh बargarh"),
        array("value" => "BHADRAK", "text" => "Bhadrak भद्रक"),
        array("value" => "BOUDH", "text" => "Boudh बौध"),
        array("value" => "Cuttack", "text" => "Cuttack कटक"),
        array("value" => "DEOGARH", "text" => "Deogarh देवगढ़"),
        array("value" => "DHENKANAL", "text" => "Dhenkanal ढेंकानल"),
        array("value" => "Gajapati", "text" => "Gajapati गजपती"),
        array("value" => "GANJAM", "text" => "Ganjam गंजाम"),
        array("value" => "JAGATSINGHPUR", "text" => "Jagatsinghpur जगतसिंहपुर"),
        array("value" => "JHARSUGUDA", "text" => "Jharsuguda झारसुगुड़ा"),
        array("value" => "KALAHANDI", "text" => "Kalahandi कालाहांडी"),
        array("value" => "KANDHAMAL", "text" => "Kandhamal कंधमाल"),
        array("value" => "KENDRAPARA", "text" => "Kendrapara केन्द्रीय"),
        array("value" => "KENDUJHAR", "text" => "Keonjhar केओंज़हर"),
        array("value" => "KHURDA", "text" => "Khordha खुर्दा"),
        array("value" => "KORAPUT", "text" => "Koraput कोरापुट"),
        array("value" => "MALKANGIRI", "text" => "Malkangiri मालकानगिरी"),
        array("value" => "MAYURBHANJ", "text" => "Mayurbhanj मयूरभंज"),
        array("value" => "NAWARANGPUR", "text" => "Nabarangpur नवांगपुर"),
        array("value" => "NAYAGARH", "text" => "Nayagarh नयागढ़"),
        array("value" => "NUAPADA", "text" => "Nuapada नुआपड़ा"),
        array("value" => "PURI", "text" => "Puri पुरी"),
        array("value" => "RAYAGADA", "text" => "Rayagada रायगढ़"),
        array("value" => "SAMBALPUR", "text" => "Sambalpur संभलपुर"),
        array("value" => "SONEPUR", "text" => "Sonepur सोनपुर"),
        array("value" => "KHURDA", "text" => "Khurda खुर्दा"),
        array("value" => "TALCHER", "text" => "Talcher तालचर"),
        array("value" => "DEOGARH", "text" => "Deogarh देवगढ़"),
        array("value" => "BHADRAK", "text" => "Bhadrak भद्रक")
    );
} else if ($state == "PUNJAB") {

    $districts = array(
        array("value" => "AMRITSAR", "text" => "Amritsar अमृतसर"),
        array("value" => "BARNALA", "text" => "Barnala बARNALA"),
        array("value" => "BATHINDA", "text" => "Bathinda बठिंडा"),
        array("value" => "FEROZEPUR", "text" => "Ferozepur फिरोजपुर"),
        array("value" => "FATEHGARH SAHIB", "text" => "Fatehgarh Sahib फतेहगढ़ साहिब"),
        array("value" => "GURDASPUR", "text" => "Gurdaspur गुरदासपुर"),
        array("value" => "HOSHIARPUR", "text" => "Hoshiarpur होशियारपुर"),
        array("value" => "JALANDHAR", "text" => "Jalandhar जलंधर"),
        array("value" => "KAPURTHALA", "text" => "Kapurthala कपूरथला"),
        array("value" => "LUDHIANA", "text" => "Ludhiana लुधियाना"),
        array("value" => "MOGA", "text" => "Moga मोगा"),
        array("value" => "MUKTSAR", "text" => "Muktsar मुक्तसर"),
        array("value" => "PATIALA", "text" => "Patiala पटियाला"),
        array("value" => "RUPNAGAR", "text" => "Rupnagar रुपनगर"),
        array("value" => "SANGRUR", "text" => "Sangrur संगरूर"),
        array("value" => "SBS NAGAR", "text" => "SBS Nagar (Nawanshahr) नवांशहर"),
        array("value" => "SRI MUKTSAR SAHIB", "text" => "Sri Muktsar Sahib श्री मुक्तसर साहिब"),
        array("value" => "TARN TARAN", "text" => "Tarn Taran तरन तारन")
    );
} else if ($state == "RAJASTHAN") {

    $districts = array(
        array("value" => "AJMER", "text" => "Ajmer अजमेर"),
        array("value" => "ALWAR", "text" => "Alwar अलवर"),
        array("value" => "BANSWARA", "text" => "Banswara बांसवाड़ा"),
        array("value" => "BARAN", "text" => "Baran बारां"),
        array("value" => "BARMER", "text" => "Barmer बाड़मेर"),
        array("value" => "BHARATPUR", "text" => "Bharatpur भरतपुर"),
        array("value" => "BHILWARA", "text" => "Bhilwara भीलवाड़ा"),
        array("value" => "BUNDI", "text" => "Bundi बूँदी"),
        array("value" => "CHITTORGARH", "text" => "Chittorgarh चित्तौड़गढ़"),
        array("value" => "DAUSA", "text" => "Dausa दौसा"),
        array("value" => "DHOLPUR", "text" => "Dholpur धोलपुर"),
        array("value" => "TONK", "text" => "Tonk टोंक"),
        array("value" => "JODHPUR", "text" => "Jodhpur जोधपुर"),
        array("value" => "JHALAWAR", "text" => "Jhalawar झालावार"),
        array("value" => "JAIPUR", "text" => "Jaipur जयपुर"),
        array("value" => "JHUNJHUNU", "text" => "Jhunjhunu झुंझुनू"),
        array("value" => "KARAULI", "text" => "Karauli करौली"),
        array("value" => "KOTA", "text" => "Kota कोटा"),
        array("value" => "NAGAUR", "text" => "Nagaur नागौर"),
        array("value" => "PALI", "text" => "Pali पाली"),
        array("value" => "RAJSAMAND", "text" => "Rajsamand राजसमंद"),
        array("value" => "SAWAI MADHOPUR", "text" => "Sawai Madhopur सवाई माधोपुर"),
        array("value" => "SIROHI", "text" => "Sirohi सिरोही"),
        array("value" => "TONK", "text" => "Tonk टोंक"),
        array("value" => "UDAIPUR", "text" => "Udaipur उदयपुर"),
        array("value" => "JODHPUR", "text" => "Jodhpur जोधपुर")
    );
} else if ($state == "SIKKIM") {

    $districts = array(
        array("value" => "EAST", "text" => "East Sikkim पूर्व सिक्किम"),
        array("value" => "WEST", "text" => "West Sikkim पश्चिम सिक्किम"),
        array("value" => "NORTH", "text" => "North Sikkim उत्तर सिक्किम"),
        array("value" => "SOUTH", "text" => "South Sikkim दक्षिण सिक्किम")
    );
} else if ($state == "TAMIL NADU") {
    $districts = array(
        array("value" => "CHENNAI", "text" => "Chennai चेन्नई"),
        array("value" => "CUDDALORE", "text" => "Cuddalore कड्डालोर"),
        array("value" => "DHARMAPURI", "text" => "Dharmapuri धर्मपुरी"),
        array("value" => "DINDIGUL", "text" => "Dindigul दिंडीगुल"),
        array("value" => "ERODE", "text" => "Erode एरोड"),
        array("value" => "KALLAKURICHI", "text" => "Kallakurichi कळ्लाकुरीची"),
        array("value" => "KANCHIPURAM", "text" => "Kanchipuram कांचीपुरम"),
        array("value" => "KARUR", "text" => "Karur करूर"),
        array("value" => "KRISHNAGIRI", "text" => "Krishnagiri कृष्णागिरी"),
        array("value" => "MADURAI", "text" => "Madurai मदुरई"),
        array("value" => "NAMAKKAL", "text" => "Namakkal नमक्कल"),
        array("value" => "PERAMBALUR", "text" => "Perambalur पेरम्बलूर"),
        array("value" => "PUDUKOTTAI", "text" => "Pudukkottai पुदुकोट्टाई"),
        array("value" => "RAMANATHAPURAM", "text" => "Ramanathapuram रामनाथपुरम"),
        array("value" => "SALEM", "text" => "Salem सलेम"),
        array("value" => "SIVAGANGA", "text" => "Sivaganga शिवगंगा"),
        array("value" => "THANJAVUR", "text" => "Thanjavur तंजावुर"),
        array("value" => "THENI", "text" => "Theni थेनी"),
        array("value" => "TIRUCHIRAPPALLI", "text" => "Tiruchirappalli तिरुचिरापल्ली"),
        array("value" => "TIRUNELVELI", "text" => "Tirunelveli तिरुनेल्वेली"),
        array("value" => "TIRUVALLUR", "text" => "Tiruvallur तिरुवल्लूर"),
        array("value" => "TIRUPPUR", "text" => "Tiruppur तिरुप्पुर"),
        array("value" => "VELLORE", "text" => "Vellore वेल्लोर"),
        array("value" => "VIRUDHUNAGAR", "text" => "Virudhunagar विरुधुनगर"),
        array("value" => "COIMBATORE", "text" => "Coimbatore कोयम्बटूर"),
        array("value" => "TUTICORIN", "text" => "Tuticorin तूतिकोरीन"),
        array("value" => "KANYAKUMARI", "text" => "Kanyakumari कन्याकुमारी"),
        array("value" => "TIRUVANNAMALAI", "text" => "Tiruvannamalai तिरुवन्नामलई"),
        array("value" => "VILLUPURAM", "text" => "Villupuram विलुप्पुरम"),
        array("value" => "RANIPET", "text" => "Ranipet रानीपेट"),
        array("value" => "TIRUPUR", "text" => "Tirupur तिरुप्पुर"),
        array("value" => "CUDDALORE", "text" => "Cuddalore कड्डालोर"),
        array("value" => "KANCHIPURAM", "text" => "Kanchipuram कांचीपुरम"),
        array("value" => "KANYAKUMARI", "text" => "Kanyakumari कन्याकुमारी"),
        array("value" => "MADURAI", "text" => "Madurai मदुरई")
    );
} else if ($state == "TELANGANA") {
    $districts = array(
        array("value" => "ADILABAD", "text" => "Adilabad आदिलाबाद"),
        array("value" => "HYDERABAD", "text" => "Hyderabad हैदराबाद"),
        array("value" => "JAGTIAL", "text" => "Jagtial जगतियाल"),
        array("value" => "JANGAON", "text" => "Jangaon जंगांव"),
        array("value" => "KHAMMAM", "text" => "Khammam खम्मम"),
        array("value" => "KOMARAM BHEEM", "text" => "Komaram Bheem कोमाराम भीम"),
        array("value" => "KOTHAGUDEM", "text" => "Kothagudem कोथगुड़ेम"),
        array("value" => "MAHABUBABAD", "text" => "Mahabubabad महबूबाबाद"),
        array("value" => "MAHABUBNAGAR", "text" => "Mahabubnagar महबूबनगर"),
        array("value" => "MANCHERIAL", "text" => "Mancherial मंछेरियल"),
        array("value" => "MEDAK", "text" => "Medak मेदक"),
        array("value" => "MEDCHAL", "text" => "Medchal मेडचल"),
        array("value" => "MULUGU", "text" => "Mulugu मुलुगु"),
        array("value" => "NAGARKURNOOL", "text" => "Nagarkurnool नागरकुरनूल"),
        array("value" => "NARAYANAPET", "text" => "Narayanpet नारायणपेट"),
        array("value" => "NIRMAL", "text" => "Nirmal निर्मल"),
        array("value" => "NIZAMABAD", "text" => "Nizamabad निजामाबाद"),
        array("value" => "Peddapalli", "text" => "Peddapalli पेद्दापल्ली"),
        array("value" => "RAJANNA SIRCILLA", "text" => "Rajanna Sircilla राजन्ना सिरसिल्ला"),
        array("value" => "RANGAREDDY", "text" => "Rangareddy रंगारेड्डी"),
        array("value" => "SANGAREDDY", "text" => "Sangareddy संगारेड्डी"),
        array("value" => "SIDDIPET", "text" => "Siddipet सिद्धिपेट"),
        array("value" => "SURYAPET", "text" => "Suryapet सूरयपेट"),
        array("value" => "VIKARABAD", "text" => "Vikarabad विकाराबाद"),
        array("value" => "WARANGAL RURAL", "text" => "Warangal Rural वारंगल ग्रामीण"),
        array("value" => "WARANGAL URBAN", "text" => "Warangal Urban वारंगल शहरी"),
        array("value" => "YADADRI BHONGIR", "text" => "Yadadri Bhongir यदाद्री भोंगीर"),
        array("value" => "KHAMMAM", "text" => "Khammam खम्मम"),
        array("value" => "SANGAREDDY", "text" => "Sangareddy संगारेड्डी"),
        array("value" => "NIZAMABAD", "text" => "Nizamabad निजामाबाद"),
        array("value" => "MEDCHAL", "text" => "Medchal मेडचल")
    );
} else if ($state == "TRIPURA") {

    $districts = array(
        array("value" => "WEST", "text" => "West Tripura पश्चिम त्रिपुरा"),
        array("value" => "SEPAHIJALA", "text" => "Sepahijala सेपाहीजाला"),
        array("value" => "KHOWAI", "text" => "Khowai खोवाई"),
        array("value" => "GOMATI", "text" => "Gomati गोमती"),
        array("value" => "UNAKOTI", "text" => "Unakoti उनाकोटी"),
        array("value" => "DHALAI", "text" => "Dhalai धलाई"),
        array("value" => "SOUTH", "text" => "South Tripura दक्षिण त्रिपुरा"),
        array("value" => "NORTH", "text" => "North Tripura उत्तर त्रिपुरा")
    );
} else if ($state == "UTTARAKHAND") {
    $districts = array(
        array("value" => "ALMORA", "text" => "Almora अल्मोड़ा"),
        array("value" => "BAGESHWAR", "text" => "Bageshwar बागेश्वर"),
        array("value" => "BAREILLY", "text" => "Bareilly बरेली"),
        array("value" => "CHAMOLI", "text" => "Chamoli चमोली"),
        array("value" => "CHAMPAVAT", "text" => "Champawat चम्पावत"),
        array("value" => "DEHRA DUN", "text" => "Dehradun देहरादून"),
        array("value" => "HARIDWAR", "text" => "Haridwar हरिद्वार"),
        array("value" => "NAINITAL", "text" => "Nainital नैनीताल"),
        array("value" => "PAURI GARHWAL", "text" => "Pauri Garhwal पौड़ी गढ़वाल"),
        array("value" => "PITHORAGARH", "text" => "Pithoragarh पिथौरागढ़"),
        array("value" => "RUDRAPRAYAG", "text" => "Rudraprayag रुद्रप्रयाग"),
        array("value" => "TEHRI GARHWAL", "text" => "Tehri Garhwal टिहरी गढ़वाल"),
        array("value" => "UTTARKASHI", "text" => "Uttarkashi उत्तरकाशी")
    );
} else if ($state == "WEST BENGAL") {
    $districts = array(
        array("value" => "ALIPURDUAR", "text" => "Alipurduar अलीपुरद्वार"),
        array("value" => "BANKURA", "text" => "Bankura बांकुरा"),
        array("value" => "BIRBHUM", "text" => "Birbhum बर्धमान"),
        array("value" => "PURULIA", "text" => "Purulia पुरुलिया"),
        array("value" => "MURSHIDABAD", "text" => "Murshidabad मुर्शिदाबाद"),
        array("value" => "MALDA", "text" => "Malda मालदा"),
        array("value" => "NORTH_24_PARGANAS", "text" => "North 24 Parganas उत्तर 24 परगना"),
        array("value" => "SOUTH_24_PARGANAS", "text" => "South 24 Parganas दक्षिण 24 परगना"),
        array("value" => "HOWRAH", "text" => "Howrah हावड़ा"),
        array("value" => "HOOGHLY", "text" => "Hooghly हुगली"),
        array("value" => "KOLKATA", "text" => "Kolkata कोलकाता"),
        array("value" => "NADIA", "text" => "Nadia नदिया"),
        array("value" => "NORTH_DINAJPUR", "text" => "North Dinajpur उत्तर दिनाजपुर"),
        array("value" => "SOUTH_DINAJPUR", "text" => "South Dinajpur दक्षिण दिनाजपुर"),
        array("value" => "JALPAIGURI", "text" => "Jalpaiguri जलपाईगुड़ी"),
        array("value" => "KOCH_BEHAR", "text" => "Koch Behar कूच बिहार"),
        array("value" => "DARBHANGA", "text" => "Darbhanga दरभंगा"),
        array("value" => "PURBA_MEDINIPUR", "text" => "Purba Medinipur पूर्व मेदिनीपुर"),
        array("value" => "PASCHIM_MEDINIPUR", "text" => "Paschim Medinipur पश्चिम मेदिनीपुर"),
        array("value" => "JHARGRAM", "text" => "Jhargram झारग्राम")
    );
} else if ($state == "CHANDIGARH") {
} else if ($state == "DADRA & NAGAR HAVELI AND DAMAN & DIU") {
} else if ($state == "DELHI") {
} else if ($state == "JAMMU & KASHMIR") {
} else if ($state == "LADAKH") {
} else if ($state == "LAKSHADWEEP") {
}

header('Content-Type: application/json');
echo json_encode($districts);
